# Copyright 2012-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# http://aws.amazon.com/asl/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateStackStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateStackStateMachineTask
      Handler: create_stack.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  CheckStackExistsStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CheckStackExistsStateMachineTask
      Handler: check_stack_exists.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  CreateChangeSetStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateChangeSetStateMachineTask
      Handler: create_change_set.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  CheckStackCreationStatusStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CheckStackCreationStatusStateMachineTask
      Handler: check_stack_creation_status.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  CheckChangeSetCreationStatusStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CheckChangeSetCreationStatusStateMachineTask
      Handler: check_change_set_creation_status.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  ExecuteChangeSetStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ExecuteChangeSetStateMachineTask
      Handler: execute_change_set.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  InspectChangeSetStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: InspectChangeSetStateMachineTask
      Handler: inspect_change_set.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  DeleteChangeSetStateMachineTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteChangeSetStateMachineTask
      Handler: delete_change_set.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::665243897136:role/hello-lambda-role
  